# Generated by Django 2.2.4 on 2019-08-23 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AWSKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('aws_access_key_id', models.TextField()),
                ('aws_secret_access_key', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cron',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('minute', models.CharField(max_length=32)),
                ('hour', models.CharField(max_length=32)),
                ('day_of_week', models.CharField(max_length=32)),
                ('day_of_month', models.CharField(max_length=32)),
                ('month_of_year', models.CharField(max_length=32)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Restore',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('backup', models.ForeignKey(help_text='The backup to restore', on_delete=django.db.models.deletion.PROTECT, to='main.Backup')),
                ('cron', models.ForeignKey(help_text='How often to test restore', on_delete=django.db.models.deletion.PROTECT, to='main.Cron')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SSHKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=128)),
                ('private_key', models.TextField()),
                ('username', models.CharField(max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DumpBackup',
            fields=[
                ('backup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='dump', serialize=False, to='main.Backup')),
                ('gzip', models.PositiveSmallIntegerField(choices=[(0, 'Do not compress backup'), (1, 'Gzip on the server (less data transferred)'), (2, 'Gzip on the client (less server CPU / RAM)')], help_text='How to compress dump')),
                ('single_transaction', models.BooleanField(default=True, help_text='Use transaction to avoid locking')),
                ('grants', models.BooleanField(default=True, help_text='Dump grants to portable format, no need to backup mysql database')),
                ('routines', models.BooleanField(default=True, help_text='Backup stored procedures and functions')),
            ],
            options={
                'abstract': False,
            },
            bases=('main.backup',),
        ),
        migrations.CreateModel(
            name='FullBackup',
            fields=[
                ('backup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='full', serialize=False, to='main.Backup')),
            ],
            options={
                'abstract': False,
            },
            bases=('main.backup',),
        ),
        migrations.CreateModel(
            name='LocalDestination',
            fields=[
                ('destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='local', serialize=False, to='main.Destination')),
                ('path', models.TextField()),
            ],
            options={
                'abstract': False,
            },
            bases=('main.destination',),
        ),
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=64)),
                ('host', models.GenericIPAddressField()),
                ('port', models.PositiveSmallIntegerField()),
                ('mysql_user', models.CharField(max_length=64)),
                ('mysql_pass', models.CharField(max_length=64)),
                ('ssh_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.SSHKey')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RestoreResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField()),
                ('finished', models.DateTimeField()),
                ('bytes', models.PositiveIntegerField()),
                ('table_count', models.PositiveIntegerField()),
                ('row_count', models.PositiveIntegerField()),
                ('routine_count', models.PositiveIntegerField()),
                ('log', models.FileField(upload_to='')),
                ('restore', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Restore')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='restore',
            name='server',
            field=models.ForeignKey(help_text='The server to restore to', on_delete=django.db.models.deletion.PROTECT, to='main.Server'),
        ),
        migrations.CreateModel(
            name='DestinationFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('identifier', models.CharField(max_length=128)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Destination')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('jobs', models.ManyToManyField(related_name='databases', to='main.Backup')),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Server')),
            ],
        ),
        migrations.CreateModel(
            name='BackupResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started', models.DateTimeField()),
                ('finished', models.DateTimeField()),
                ('bytes', models.PositiveIntegerField()),
                ('table_count', models.PositiveIntegerField()),
                ('row_count', models.PositiveIntegerField()),
                ('routine_count', models.PositiveIntegerField()),
                ('log', models.FileField(upload_to='')),
                ('backup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Backup')),
                ('destination_file', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.DestinationFile')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='backup',
            name='cron',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Cron'),
        ),
        migrations.AddField(
            model_name='backup',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.Destination'),
        ),
        migrations.AddField(
            model_name='backup',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Server'),
        ),
        migrations.CreateModel(
            name='S3Destination',
            fields=[
                ('destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='s3', serialize=False, to='main.Destination')),
                ('s3_bucket_name', models.CharField(max_length=128)),
                ('aws_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.AWSKey')),
            ],
            options={
                'abstract': False,
            },
            bases=('main.destination',),
        ),
        migrations.CreateModel(
            name='RemoteDestination',
            fields=[
                ('destination', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='remote', serialize=False, to='main.Destination')),
                ('host', models.CharField(max_length=128)),
                ('path', models.TextField()),
                ('ssk_key', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.SSHKey')),
            ],
            options={
                'abstract': False,
            },
            bases=('main.destination',),
        ),
        migrations.CreateModel(
            name='IncrementalBackup',
            fields=[
                ('backup', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='incremental', serialize=False, to='main.Backup')),
                ('base', models.ForeignKey(help_text='The full backup that this increment extends', on_delete=django.db.models.deletion.CASCADE, related_name='increments', to='main.FullBackup')),
            ],
            options={
                'abstract': False,
            },
            bases=('main.backup',),
        ),
    ]
